<a href="https://colab.research.google.com/github/madakixo/Car-Price-Prediction/blob/master/keras_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.2


In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.52946043, -0.60124373,  0.6803205 , -0.8336862 , -1.7844887 ,
        -0.11948028, -0.43979406,  0.11378188,  0.05745614, -0.15823808]],
      dtype=float32)

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.1808742 , 0.05838725, 0.21032666, 0.04627747, 0.01788304,
        0.0945247 , 0.06861748, 0.1193575 , 0.11282044, 0.09093121]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss_fn(y_train[:1], predictions).numpy()

2.3588943

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2919 - accuracy: 0.9146
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1395 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1086 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0873 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0767 - accuracy: 0.9760


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0723 - accuracy: 0.9780 - 602ms/epoch - 2ms/step


[0.07226221263408661, 0.9779999852180481]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.31490755e-08, 2.02749195e-08, 9.79948745e-05, 3.97245240e-05,
        1.46919612e-11, 4.17631218e-09, 4.68289483e-14, 9.99856234e-01,
        9.47050069e-07, 5.10994869e-06],
       [1.24962742e-08, 1.96749883e-04, 9.99802291e-01, 8.54786265e-07,
        2.13863808e-14, 3.47263445e-08, 5.26728279e-08, 4.58430020e-14,
        9.24960872e-08, 1.54220453e-15],
       [3.39110983e-07, 9.99322057e-01, 5.54077633e-05, 3.15498187e-06,
        4.34025824e-05, 7.62347645e-06, 7.56397731e-06, 4.15089075e-04,
        1.44933103e-04, 4.57020946e-07],
       [9.99784172e-01, 3.92115140e-09, 1.61186486e-04, 3.30487865e-06,
        4.61715786e-07, 4.40358735e-06, 1.08550530e-05, 9.25250242e-06,
        6.46529656e-08, 2.62599260e-05],
       [1.65125039e-06, 1.08435025e-07, 1.30288563e-05, 1.32185775e-07,
        9.94125962e-01, 4.78534321e-06, 2.22417675e-05, 1.42491073e-04,
        6.73524801e-06, 5.68279019e-03]], dtype=float32)>